# Plugwise Pi Configuration Example
# Copy this file to config.yaml and modify as needed

# Plugwise device configuration
plugwise:
  # Network settings for Plugwise devices
  network:
    interface: "eth0"  # Network interface to use
    timeout: 30        # Connection timeout in seconds
    retry_attempts: 3  # Number of retry attempts
  
  # Device definitions
  devices:
    - name: "Living Room Circle"
      mac_address: "00:01:02:03:04:05"
      type: "circle"
      location: "Living Room"
      description: "Main living room power monitoring"
      
    - name: "Kitchen Circle"
      mac_address: "00:01:02:03:04:06"
      type: "circle"
      location: "Kitchen"
      description: "Kitchen appliances monitoring"
      
    - name: "Bedroom Circle"
      mac_address: "00:01:02:03:04:07"
      type: "circle"
      location: "Bedroom"
      description: "Bedroom power monitoring"
  
  # Data collection settings
  collection:
    interval: 60       # Data collection interval in seconds
    batch_size: 100    # Number of readings to batch before saving
    max_retries: 3     # Maximum retries for failed collections

# Database configuration
database:
  # Database type: sqlite or postgresql
  type: "sqlite"
  
  # SQLite configuration
  sqlite:
    path: "data/plugwise.db"
    timeout: 30
  
  # PostgreSQL configuration (uncomment if using PostgreSQL)
  # postgresql:
  #   host: "localhost"
  #   port: 5432
  #   name: "plugwise"
  #   user: "plugwise_user"
  #   password: "your_secure_password"
  #   pool_size: 10
  #   max_overflow: 20

# API configuration
api:
  host: "0.0.0.0"     # Bind to all interfaces
  port: 8080           # API port
  debug: false         # Enable debug mode
  cors_origins:        # CORS allowed origins
    - "http://localhost:3000"
    - "http://localhost:8080"
  rate_limit:          # Rate limiting
    requests_per_minute: 100
    burst_size: 20

# Logging configuration
logging:
  level: "INFO"        # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/plugwise.log"
  max_size: "10MB"     # Maximum log file size
  backup_count: 5      # Number of backup files to keep
  console: true        # Also log to console

# Monitoring and metrics
monitoring:
  enabled: true
  prometheus_port: 9090
  health_check_interval: 300  # Health check interval in seconds
  
  # Alerting thresholds
  alerts:
    device_offline_threshold: 300  # Seconds before device considered offline
    high_power_threshold: 5000     # Watts before high power alert
    low_battery_threshold: 20      # Percentage before low battery alert

# Data retention and cleanup
data_management:
  retention_days: 365   # Keep data for this many days
  cleanup_interval: 86400  # Cleanup interval in seconds (24 hours)
  compression_enabled: true  # Enable data compression for old records

# Security settings
security:
  api_key_required: false  # Require API key for all requests
  allowed_ips: []          # List of allowed IP addresses (empty = all)
  ssl_enabled: false       # Enable SSL/TLS
  # ssl_cert: "path/to/cert.pem"
  # ssl_key: "path/to/key.pem"

# Development settings
development:
  mock_devices: false      # Use mock devices for testing
  fake_data: false         # Generate fake data for testing
  verbose_logging: false 